name: Github Slack Notify

on: 
  push:
    branches:[ master ]
jobs:
  slackNotification:
  
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: drilonrecica/action-slack-notify@0.0.3
      env:
        SLACK_TOKEN: ${{ secrets.SLACK_TOKEN }}